apiVersion: apps/v1
kind: Deployment
metadata:
  name: sean-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sean-api
  template:
    metadata:
      labels:
        app: sean-api
    spec:
      containers:
        - name: sean-api
          image: us-docker.pkg.dev/april-2023-online-cit-262/sean-api/api-tests
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10